### ISSUE TITLE
文档错误JAnalyticsPackage中没有init方法

### ISSUE THREAD

**Issue by kala888** [jpush/janalytics-react-native#11]
![image](https://user-images.githubusercontent.com/1215976/32827389-ffdd9bac-ca26-11e7-9efa-b9c878760660.png)

![image](https://user-images.githubusercontent.com/1215976/32827563-97278e78-ca27-11e7-91a8-e0a7ae1638fd.png)

**Comment by KenChoi1992** [comment]
@kala888 需要调用 JAnalyticsInterface.init(this)
