### ISSUE TITLE
android中没有 uploadLocation方法吗

### ISSUE THREAD

**Issue by giantss** [jpush/janalytics-react-native#12]
在android中调用 JAnalyticsModule.uploadLocation({latitude: 0.4, longitude: 0.5}) 报错`undefined is not a function JAnalyticsModule.uploadLocation(params)`
如果没有的话，还麻烦在文档中标注一下 `Android Only`
![image](https://user-images.githubusercontent.com/13778798/33228154-6082aaa4-d1ef-11e7-8ef7-4d7009e79d2c.png)

**Comment by KenChoi1992** [comment]
@giantss Android 没有这个方法，文档已经更新。
