### ISSUE TITLE
IOS JAnalyticsModule is undefined

### ISSUE THREAD

**Issue by kala888** [jpush/janalytics-react-native#14]
可以打包成功，启动时报错

    "janalytics-react-native": "^1.1.0",
    "jcore-react-native": "^1.2.2",
    "jpush-react-native": "^2.1.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",

![image](https://user-images.githubusercontent.com/1215976/33478935-053a7cb8-d6c6-11e7-9d83-ba9982001c30.png)

![image](https://user-images.githubusercontent.com/1215976/33478332-e49183dc-d6c3-11e7-94d5-6c46c64b6b6a.png)

@KenChoi1992

**Comment by huangminlinux** [comment]
JAnalyticsModule 成功 link 了没

**Comment by kala888** [comment]
@huangminlinux  应该是link成功了

![image](https://user-images.githubusercontent.com/1215976/33707983-26fa733c-db74-11e7-8383-534fe1b97b82.png)

怀疑这里const JAnalyticsModule = NativeModules.JAnalyticsModule 有问题，
![image](https://user-images.githubusercontent.com/1215976/33707965-1f1c5f0e-db74-11e7-9498-5f56a3c3bf6b.png)

**Comment by huangminlinux** [comment]
奇怪使用 demo 没出现这种问题。

**Comment by kala888** [comment]
日狗了，没有那个.a文件
手动拖过来就对了，对于小白，这是多么痛的领悟
![image](https://user-images.githubusercontent.com/1215976/33708730-3f6d45e6-db76-11e7-9617-774ca4f2c916.png)

**Comment by huangminlinux** [comment]
react-native link 成功会自动添加的。

**Comment by kala888** [comment]
@huangminlinux link了n遍，没有添加，我弄了好几天了。。。。

**Comment by kala888** [comment]
Link的问题，运行时刻 NativeModules并没有JAnalyticsModule，手动添加libRTCJAnalyticsModule.a 到link binary，解决
