### ISSUE TITLE
可以添加 podspec 文件以便使用 pod 安装吗

### ISSUE THREAD

**Issue by Riant** [jpush/janalytics-react-native#18]
如题，在根据 RN 文件手动 link 之后，Build 失败，引发一堆错误，所以想请作者帮忙实现一下 podspec 文件，这样的话，可以造福一下为集成 RN 到其他原生项目中而使用 pod 管理 RN 及其组件同学。

谢谢。

**Comment by Riant** [comment]
额，发现 Cocopods 官方库里边已经包含 jcore, janalytics 之类之类官方库描述文件了，只是，与 github 这边的版本比较，有的靠前，有的落后 :(

**Comment by Riant** [comment]
额，是 jcore, janalytics, 不是 janalytics-react-native，不是版本错乱，不好意思，所以，还是想问问能否也为  janalytics-react-native 等提供 pod 安装支持喃。

谢谢。

**Comment by huangminlinux** [comment]
ok, 下个版本中支持。

**Comment by Riant** [comment]
坐等 :D

**Comment by huangminlinux** [comment]
可以更新到：
[jcore-react-native](https://github.com/jpush/jcore-react-native/releases/tag/1.2.4) 
[jpush-react-native](https://github.com/jpush/jpush-react-native/releases/tag/untagged-77a3bb4af8a22fd1e31c)  
[jmessage-react-plugin](https://github.com/jpush/jmessage-react-plugin/releases/tag/2.2.1) 
[janalytics-react-native](https://github.com/jpush/janalytics-react-native/releases/tag/1.1.1) 
[jshare-react-native](https://github.com/jpush/jshare-react-native/releases/tag/1.1.9)

**Comment by Riant** [comment]
哈哈，非常感谢。

下午试试。
