### ISSUE TITLE
方法不会覆盖或实现超类型的方法

### ISSUE THREAD

**Issue by SinTan1071** [jpush/janalytics-react-native#22]
/janalytics-react-native/android/src/main/java/cn/jpush/reactnativejanalytics/JAnalyticsPackage.java:27:错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
1 个错误

 FAILED
:app:buildInfoGeneratorFuncDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':janalytics-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Riant** [comment]
参考 #20

移除报错所在行 @override

**Comment by SinTan1071** [comment]
谢谢
