### ISSUE TITLE
可以设置当前渠道的吗

### ISSUE THREAD

**Issue by xwartz** [jpush/janalytics-react-native#24]
因为在使用美团的多渠道打包方案(https://github.com/Meituan-Dianping/walle)，提升打包效率。
但是没有看到相关接口来动态设置当前渠道，只能读取写死在 `AndroidManifest.xml` 文件的 `JPUSH_CHANNEL` 字段吗？

**Comment by xwartz** [comment]
论坛里有不少这样的需求 https://community.jiguang.cn/t/channel/24798

希望极光能支持动态设置渠道

**Comment by KenChoi1992** [comment]
@xwartz SDK 更新的话，我们这边会跟进的。

**Comment by xwartz** [comment]
@KenChoi1992   大哥能帮忙问一下 SDK 什么时候更新吗

**Comment by JoshLipan** [comment]
更新至[v1.2.0](https://github.com/jpush/janalytics-react-native/releases/tag/1.2.0)

**Comment by xwartz** [comment]
Thanks.
