### ISSUE TITLE
发送事件之后，在极光官网的后台没有发现相关数据

### ISSUE THREAD

**Issue by quietautumn** [jpush/janalytics-react-native#28]
做了一个登陆和统计页面停留时间的统计，程序正常运行，好像没有看到接口是否成功的回调，请问怎么才能判断当前事件是否成功了呢？

**Comment by JoshLipan** [comment]
没有提供成功回调
当前统计在程序下一次开启时上报

**Comment by quietautumn** [comment]
好的，页面统计要延迟一天更新数据，已经有了，麻烦了
