### ISSUE TITLE
编译出错，最新版本，配置安装说明配置的

### ISSUE THREAD

**Issue by lhh-sofy** [jpush/janalytics-react-native#30]
<img width="952" alt="5f4190316214c3a64e537b79706b538a" src="https://user-images.githubusercontent.com/13582183/44764862-4ebf6900-ab84-11e8-9069-431ddf14a048.png">

**Comment by JoshLipan** [comment]
link成功了没

**Comment by lhh-sofy** [comment]
手动link的，该配置的也都配置了。

**Comment by JoshLipan** [comment]
两个类import了没，导入AS看下具体报错
```
import cn.jiguang.analytics.android.api.JAnalyticsInterface;
import cn.jpush.reactnativejanalytics.JAnalyticsPackage;
```

**Comment by lhh-sofy** [comment]
这个是我的所有截图。。
<img width="674" alt="776e638074a7ab8e4dca4bca418999ab" src="https://user-images.githubusercontent.com/13582183/44840901-b359f100-ac74-11e8-97de-53fad9d90e92.png">
<img width="938" alt="a7482f73c91b203f66031723bd7e8aa4" src="https://user-images.githubusercontent.com/13582183/44840902-b3f28780-ac74-11e8-9621-88dbf9e31b79.png">
<img width="479" alt="ad8c827bfa753c45c67ca0343da2a51b" src="https://user-images.githubusercontent.com/13582183/44840903-b48b1e00-ac74-11e8-91e3-f0eaa06b7b5f.png">
<img width="527" alt="af56ac69f9da01047fbe3cd6ae42c486" src="https://user-images.githubusercontent.com/13582183/44840904-b48b1e00-ac74-11e8-80e0-6acfe04e102d.png">

**Comment by JoshLipan** [comment]
参考下 #16

**Comment by lhh-sofy** [comment]
多谢，编译以及生效。请修改一下你们这边到说明文档，文档有误。。。安卓配置文档 ，最后到引用

**Comment by JoshLipan** [comment]
哪一块有误，能否详细说明下

**Comment by lhh-sofy** [comment]
<img width="943" alt="52795277-1de5-4ad3-bce5-b2c2c13155e6" src="https://user-images.githubusercontent.com/13582183/44968588-49469200-af7b-11e8-8598-b113ad4d0340.png">

**Comment by JoshLipan** [comment]
OK，谢谢，对我们帮助很大
