### ISSUE TITLE
关于崩溃日志的统计

### ISSUE THREAD

**Issue by quietautumn** [jpush/janalytics-react-native#31]
在极光后台查看的时候，安卓出现了很多崩溃的日志，但是IOS都没有，不知道是因为集成中有其他问题，还是因为没有收集ios崩溃的日志呢。

**Comment by JoshLipan** [comment]
你使用的插件版本是？还有崩溃日志详情贴一下

**Comment by quietautumn** [comment]
插件版本：
    "janalytics-react-native": "^1.1.5",
    "jcore-react-native": "^1.2.9",
    "jmessage-react-plugin": "^2.4.1",
    "jpush-react-native": "^2.2.9",
![27a3d201-1393-4a6f-a79f-484480944024](https://user-images.githubusercontent.com/16301518/45398615-81cf2580-b677-11e8-8d6b-92df0790a7bb.png)
上面圈出来的两处，两个平台都是共用的，但是下图中的ios平台一次错误日志也没有
![f25344df-a578-49ab-adc2-301a1351ffcc](https://user-images.githubusercontent.com/16301518/45398696-b8a53b80-b677-11e8-8854-80085fa23511.png)

**Comment by huangminlinux** [comment]
crashLogON 方法调用了没？

**Comment by quietautumn** [comment]
加了之后可以了
