### ISSUE TITLE
build android release apk error on RN 0.57.4

### ISSUE THREAD

**Issue by M45ter** [jpush/janalytics-react-native#32]
error when I build android release apk. 

RN version: 0.57.4

error info:

error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
C:\Users\mac\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\1fa9fb454a069a8900c7e05734ef56a4\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorEr
ror not found.

C:\Users\mac\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\1fa9fb454a069a8900c7e05734ef56a4\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorE
rror not found.

C:\Users\mac\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\1fa9fb454a069a8900c7e05734ef56a4\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/k
eyboardNavigationCluster' not found.

C:\Users\mac\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\1fa9fb454a069a8900c7e05734ef56a4\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not fo
und.

C:\Users\mac\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\1fa9fb454a069a8900c7e05734ef56a4\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/font not found.

C:\Users\mac\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\1fa9fb454a069a8900c7e05734ef56a4\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not f
ound.

error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':janalytics-react-native:verifyReleaseResources'.

**Comment by JoshLipan** [comment]
更新至[v1.2.0](https://github.com/jpush/janalytics-react-native/releases/tag/1.2.0)

**Comment by M45ter** [comment]
> 更新至[v1.2.0](https://github.com/jpush/janalytics-react-native/releases/tag/1.2.0)

thank you
