### ISSUE TITLE
setup方法可以设置为RCTJShareConfig里读取吗

### ISSUE THREAD

**Issue by CloudlessMoon** [jpush/janalytics-react-native#35]
在RN会暴露APPKEY，而且我们使用的是极光全家桶，可以加一个可选配置，在RCTJShareConfig里读取APPKEY

**Comment by huangminlinux** [comment]
下个版中，提供 plist 的配置方式。

**Comment by huangminlinux** [comment]
可以升级到 1.3.0  添加了 https://github.com/jpush/janalytics-react-native/blob/master/JiGuangConfig.plist 这个配置文件，用法和 RCTJShareConfig 一样。

setup 方法可以[参考](https://github.com/jpush/janalytics-react-native/blob/master/index.js#L22)
