### ISSUE TITLE
安卓打包安装后获取不到统计信息

### ISSUE THREAD

**Issue by basilbai** [jpush/janalytics-react-native#38]
### 安卓打包安装后获取不到统计信息，iOS正常

版本如下：
`"react-native": "0.57.3"`
`"janalytics-react-native": "^1.3.0"`
`"jcore-react-native": "^1.3.1"`

配置如下：

![image](https://user-images.githubusercontent.com/26473415/53938360-f5b02f00-40ea-11e9-8a1f-d709b53a4867.png)

![image](https://user-images.githubusercontent.com/26473415/53938385-14aec100-40eb-11e9-80cc-1df230b11ddd.png)
![image](https://user-images.githubusercontent.com/26473415/53938405-27c19100-40eb-11e9-85ac-754e2ecb2026.png)
![image](https://user-images.githubusercontent.com/26473415/53938440-47f15000-40eb-11e9-9858-a901f02bcf3a.png)
![image](https://user-images.githubusercontent.com/26473415/53938488-6bb49600-40eb-11e9-9b37-095715354ecf.png)
![image](https://user-images.githubusercontent.com/26473415/53938506-753dfe00-40eb-11e9-92ad-eb5ccfbd4e3c.png)

**Comment by basilbai** [comment]
@JoshLipan
![image](https://user-images.githubusercontent.com/26473415/53939400-e088cf80-40ed-11e9-8288-b661bdd0353a.png)
![image](https://user-images.githubusercontent.com/26473415/53939425-f6969000-40ed-11e9-8df9-09ac5f6dfc63.png)

**Comment by JoshLipan** [comment]
初始化成功了吗，原生log提供下

**Comment by basilbai** [comment]
@JoshLipan 
```
03-07 16:12:24.377 9785-9785/? D/JIGUANG-JAnalytics: [JAnalyticsInterface] JAnalyticsInterface init...version:1.2.2 ,buildId:140
03-07 16:12:24.563 9785-9785/? D/JIGUANG-JAnalytics: [JAnalyticsInterface] JAnalytics init succeed
03-07 16:14:18.910 10027-10027/com.danceproject D/JIGUANG-JAnalytics: [JAnalyticsInterface] JAnalyticsInterface init...version:1.2.2 ,buildId:140
03-07 16:14:19.412 10027-10027/com.danceproject D/JIGUANG-JAnalytics: [JAnalyticsInterface] JAnalytics init succeed
03-07 16:14:27.975 10027-10095/com.danceproject D/JIGUANG-JAnalytics: [SessionManager] onPageStart :{"page_name":"App","page_duration":0,"page_end_time":1551946467,"page_start_time":1551946467,"page_seq":1,"extra":{"page_phone_total_memory":0,"page_start_phone_avaliable_memory":820436992,"page_end_phone_avaliable_memory":0,"page_phone_rx_bytes":0,"page_phone_tx_bytes":0,"page_phone_mobile_rx_bytes":0,"page_phone_mobile_tx_bytes":0,"page_app_rx_bytes":0,"page_app_tx_bytes":0}}
03-07 16:17:22.439 10343-10343/com.danceproject D/JIGUANG-JAnalytics: [JAnalyticsInterface] JAnalyticsInterface init...version:1.2.2 ,buildId:140
03-07 16:17:22.789 10343-10343/com.danceproject D/JIGUANG-JAnalytics: [JAnalyticsInterface] JAnalytics init succeed
03-07 16:17:30.054 10343-10411/com.danceproject D/JIGUANG-JAnalytics: [SessionManager] onPageStart :{"page_name":"App","page_duration":0,"page_end_time":1551946649,"page_start_time":1551946649,"page_seq":1,"extra":{"page_phone_total_memory":0,"page_start_phone_avaliable_memory":837861376,"page_end_phone_avaliable_memory":0,"page_phone_rx_bytes":0,"page_phone_tx_bytes":0,"page_phone_mobile_rx_bytes":0,"page_phone_mobile_tx_bytes":0,"page_app_rx_bytes":0,"page_app_tx_bytes":0}}

```

**Comment by basilbai** [comment]
看信息是初始化成功了
```
JAnalyticsInterface init...version:1.2.2 ,buildId:140
JAnalytics init succeed
```
而且页面使用时间统计事件也成功了
```
onPageStart :{"page_name":"App","page_duration":0,"page_end_time":1551946467,"page_start_time":1551946467,"page_seq":1,"extra":{"page_phone_total_memory":0,"page_start_phone_avaliable_memory":820436992,"page_end_phone_avaliable_memory":0,"page_phone_rx_bytes":0,"page_phone_tx_bytes":0,"page_phone_mobile_rx_bytes":0,"page_phone_mobile_tx_bytes":0,"page_app_rx_bytes":0,"page_app_tx_bytes":0}}
```
页面使用时间统计事件代码
```
 componentDidMount() {
    if (Platform.OS === 'ios') {
      JAnalyticsModule.setup({ appKey: "e0b0bf48f0d7303b200494a7" })
    }
    JAnalyticsModule.crashLogON();
    var param = { pageName: "App" };
    JAnalyticsModule.startLogPageView(param);
  }
  componentWillUnmount() {
    var param = { pageName: "App" };
    JAnalyticsModule.stopLogPageView(param);
  }
```

**Comment by JoshLipan** [comment]
初始化成功了啊，没有数据吗，appkey提供下

**Comment by basilbai** [comment]
@JoshLipan appKey: "e0b0bf48f0d7303b200494a7"

**Comment by Lris12J** [comment]
1. 页面流是隔天刷新数据，也就是今天上报的数据在明天才可以看到。数据一般在每日凌晨五点更新，若遇到堵塞等情况以具体数据处理完的时间进行更新。
2. 你上面截图看到的未集成开发者服务SDK 的完整截图看下，是筛选的什么，注意强制刷新下，官网显示存在一定延迟

**Comment by basilbai** [comment]
> 1. 页面流是隔天刷新数据，也就是今天上报的数据在明天才可以看到。数据一般在每日凌晨五点更新，若遇到堵塞等情况以具体数据处理完的时间进行更新。
> 2. 你上面截图看到的未集成开发者服务SDK 的完整截图看下，是筛选的什么，注意强制刷新下，官网显示存在一定延迟

你好，第一个问题我了解，其实从昨天下午我就集成好了，就是等到今天看看也没有显示结果
第二个请看截图（筛选安卓平台）
![image](https://user-images.githubusercontent.com/26473415/53943798-dfa96b00-40f8-11e9-9001-342d4d246664.png)

**Comment by basilbai** [comment]
补充一下信息：


1.昨天按照官方指南集成后，IOS马上能统计到【累计用户】【今日新增】【今日活跃】三项数值，Android不行
2.我尝试清除浏览器缓存，更换浏览器，官网显示仍无结果
3.设备机型：
模拟器  Android 8.0.0
三星SM-G8750（Galaxy S 轻奢版）Android 8.0.0
华为Honor 8 Lite  Android 8.0.0

**Comment by Lris12J** [comment]
目前看数据显示，你的 Android 确实没有集成成功取到 ID 值，只有 iOS 设备的，你是仅集成了 JAnalytics 统计 SDK吗？是否有同时集成 JPush？
如果有集成 JPush，可以获取下 registrationID值。提供下更多的日志看看
另外，我看你在官网并未配置Android的包名，你配上包名看下

**Comment by basilbai** [comment]
@Lris12J 目前仅集成了 JAnalytics 统计 SDK，JAnalytics需要配置包名吗？

**Comment by basilbai** [comment]
我刚才配置了安卓包名，并集成了推送SDK，安卓可以成功统计了
这个事情很奇怪，因为我没有看到JAnalytics集成文档里面说明需要配置安卓包名
不过还好一切顺利，感谢你们的帮助！谢谢🙏
