### ISSUE TITLE
JAnalyticsInterface 找不到符号

### ISSUE THREAD

**Issue by hyteraesa** [jpush/janalytics-react-native#56]
react native 已经正确安装及link；

编译报错： JAnalyticsInterface 找不到

然后

MainApplication 中引入
import cn.jpush.reactnativejanalytics.JAnalyticsPackage;
import cn.jiguang.analytics.android.api.JAnalyticsInterface;
会报错：“错误: 程序包cn.jpush.reactnativejanalytics不存在”

**Comment by xwartz** [comment]
根据这个修改记录，https://github.com/jpush/janalytics-react-native/commit/4f086a4ca2fa45b207121a6d1517a285653baa38#diff-1349805b69ca75911aa608bb66654147

应该要把 

```
import cn.jpush.reactnativejanalytics.JAnalyticsPackage
```
改为
```
import cn.jiguang.plugins.analytics.JAnalyticsPackage
```

**Comment by hyteraesa** [comment]
谢谢 已经解决

**Comment by xwartz** [comment]
@huangminlinux 希望能在文档上加个说明
