### ISSUE TITLE
Android 无法编译通过

### ISSUE THREAD

**Issue by thethreeonee** [jpush/janalytics-react-native#8]
用最新版的 react native 和 极光统计 SDK react native 版集成时，执行 `yarn run android` 命令编译 Android 版时，报错：
```
/********/node_modules/janalytics-react-native/android/src/main/java/cn/jpush/reactnativejanalytics/JAnalyticsPackage.java:27: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
1 个错误
:janalytics-react-native:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

**Comment by thethreeonee** [comment]
去掉 @Override 后可以编译运行，但是后台始终没有看到数据。也不知道哪里可以修改应用上报策略。

**Comment by KenChoi1992** [comment]
@Murriouz 需要过1小时才能出现数据，不是实时更新的。

**Comment by thethreeonee** [comment]
@KenChoi1992 已经过去一下午了，依然没有数据。iOS 模拟器没有数据可以理解，现在 iOS 真机无法测试。Android 是在真机上跑的，不知道是不是跟我自己的修改（去掉 `@Override`）有关。

**Comment by KenChoi1992** [comment]
@Murriouz 跟 override 无关，你看看日志，看发送后有没有打印。另外他是你 app 打开后才开始上报的。

**Comment by KenChoi1992** [comment]
![image](https://user-images.githubusercontent.com/8196928/30738638-4f5318c2-9fbd-11e7-8de3-573636ac5899.png)

打开和关闭都会上报。

**Comment by thethreeonee** [comment]
打开关闭过很多次了，后台什么数据都没有

**Comment by KenChoi1992** [comment]
@Murriouz 你用的 jcore 是啥版本

**Comment by thethreeonee** [comment]
@KenChoi1992 `yarn add` 安装的最新版

**Comment by KenChoi1992** [comment]
@Murriouz 问题就出在这里，你应该指定 jcore 的版本为 1.1.5。另外 jcore 和 janalytics 版本不匹配有打印日志的。

**Comment by thethreeonee** [comment]
@KenChoi1992 所以安卓版是需要配合 jcore 1.1.5 版本使用？

**Comment by KenChoi1992** [comment]
@Murriouz 这取决于我们使用的 JAnalytics SDK 版本依赖的 jcore 是多少，一般来讲，我们都会在每个 janalytics-react-native 发布的时候注明依赖的 jcore-react-native  版本是多少。

**Comment by shihongzhi** [comment]
注释掉这个`@Override`就可以了。 

因为新版本的react native中的 ReactPackage 不在需要对createJSModules进行override。
